name: Pizza OPs CI/CD process

on:
  push:
    branches: ["feat/init-backend"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/pizza.pem
          chmod 400 ~/.ssh/pizza.pem
          ssh-keyscan ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -vvv -i ~/.ssh/pizza.pem ${{ vars.SSH_LOGIN }}@${{ vars.SSH_HOST }}

      - name: Deploy on Amazon EC2 instance
        run: |
          ssh -i ~/.ssh/pizza.pem \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ vars.SSH_LOGIN }}@${{ vars.SSH_HOST }} \
              "echo 'Hello world Amazon EC2🚀'"

      - name: Cleanup
        run: rm -rf ~/.ssh/pizza.pem
