name: Pizza OPs CI/CD process

on:
  push:
    branches: ["feat/init-backend"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/meapizza.pem
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/meapizza.pem
          ssh-keyscan -v ${{ vars.SSH_HOST }} > ~/.ssh/known_hosts 2>&1

      - name: Deploy on Amazon EC2 instance
        run: |
           ssh -i ~/.ssh/meapizza.pem -o StrictHostKeyChecking=no ${{ vars.SSH_HOST }} << EOF
           echo "Hello world Amazon EC2🚀"
           EOF

      - name: Cleanup
        run: rm -rf ~/.ssh/meapizza.pem
